// Publications — scraped from hanjunkim.co.kr/publication
// Full list of 129 papers. Earlier entries (1–31) omitted here for brevity;
// fill in from CV when provided.
const PUB_COVERS = 30; // cover images count on source site

const publications = [
  // 2026
  { n: 132, y: 2026, authors: 'Lee T, Jang WJ, Kim G, Ha G, Kim M, Park S, Lee G, Cho H-J, Zhang YS, Kim HJ*, Lee JM*',
    title: 'Cyclic mechanical stretch suppresses intrinsic apoptosis in high metastatic melanoma',
    journal: 'Materials Today Bio', vol: 'In Press', IF: 10.2, corr: true },
  { n: 131, y: 2026, authors: 'Kwon N, Hong Y, Jung S, Yoo D, Eo Y, Lee S, Jang WJ, Lee J, Lee T, Heo DN, Kim HJ, Yoon J, Kwon IK, Yang H, Min J, Yang DH',
    title: 'Fabrication of Transparent Microneedle Patch for Minimally Invasive Glucose Monitoring Optical Biosensor',
    journal: 'Small Structures', vol: 'In Press' },
  { n: 130, y: 2026, authors: 'Lee NK, Wang C-P, Lee S-H, Chun NY, Oh YJ, Batjargal U, Kim M-S, Jang WJ, Kim HJ, Park TE, Park W, Park CG, Kim SN',
    title: 'Resiquimod-Loaded MOF525 Enables Synergistic Photodynamic Therapy and Immunotherapy for Colorectal Cancer',
    journal: 'Nano Convergence', vol: 'In Press', link: 'https://doi.org/10.1186/s40580-026-00544-2' },
  { n: 129, y: 2026, authors: 'Choi Y, Jang W, Kang R, Batjargal U, Song J, Park S, Kim MS, Cho H, Kim J, Zhang YS, Kim HJ*, Lee J*',
    title: 'Developmentally Inspired, Mechanical–Metabolic Dual Gradient Osteochondral Constructs Bridging Regeneration and Therapeutic Screening',
    journal: 'Advanced Science', vol: 'e166602', IF: 14.1, corr: true, hanbitsa: true,
    link: 'https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/advs.202516602' },
  { n: 128, y: 2026, authors: 'Kim SH, Lee S, Kim HJ, Lee JS, Lee SJ, Nah H, Min SJ, Bang JB, Yang DH, Kim WJ, Kwon IK, Heo DN',
    title: '3D-printable, heat-resistant polycaprolactone-based polymer scaffold for sustained NO release in tissue engineering applications',
    journal: 'Colloids and Surfaces B: Biointerfaces', vol: '261;115447',
    link: 'https://www.sciencedirect.com/science/article/pii/S0927776526000354?dgcid=coauthor' },
  { n: 127, y: 2026, authors: 'Kim G, Jang W, Lee G, Ha G, Batjargal U, Park S, Kim MS, Kang R, Lee T, Song J, Lee Y, Nasiri R, Cho HJ, Zhang YS, Kim HJ*, Lee J*',
    title: 'Bidirectional Mechanical Stimulation Enables Biomechanical Coupling and Functional Maturation in Arterial Microphysiological Systems',
    journal: 'Advanced Healthcare Materials', vol: 'e05915', IF: 9.6, corr: true, hanbitsa: true,
    link: 'https://advanced.onlinelibrary.wiley.com/doi/abs/10.1002/adhm.202505915' },
  { n: 126, y: 2026, authors: 'Choi JH#, Nah H#, Kim HJ#, Min SJ, Lee D, An SH, Cho W, Moon SH, Do SH, Kwon IK*, Yang DH*, Heo DN*',
    title: 'A mechanically tunable photo-cured hydrogel system based on methacrylated collagen-keratin inter-penetrating networks for rapid and enhanced wound healing',
    journal: 'International Journal of Biological Macromolecules', vol: '349;150897', IF: 8.5, cofirst: true,
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0141813026008238' },
  { n: 125, y: 2025, authors: 'Han WB, Han S, Ko GJ, Batjargal U, Jang W, Naganaboina VR, Kim HJ*, Hwang SW*',
    title: 'A Hierarchically Structured, Stretchable, Anti‐Biofouling Encapsulation for Biodegradable Electronics',
    journal: 'Advanced Healthcare Materials', vol: 'e03622', IF: 9.6, corr: true, hanbitsa: true,
    link: 'https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/adhm.202503622' },
  { n: 124, y: 2025, authors: 'Yoo JH, Yang DH, Choi JH, Nah H, Cho W, Lee SY, Lee JS, Kim HJ, Jung GJ, Chun HJ, Heo DN, Kwon IK',
    title: 'Sprayable, crosslinker-free, and in situ-forming Schiff-based hydrogels based on oxidized sodium alginate and carbohydrazide-modified gelatin for rapid hemostasis',
    journal: 'Carbohydrate Polymers', vol: '124571',
    link: 'https://www.sciencedirect.com/science/article/pii/S0144861725013554' },
  { n: 123, y: 2025, authors: 'Kim D, Ha G, Kim M, Kwak M, Kim HJ*, Lee J*',
    title: 'Geometry-Guided Osteogenesis in Bone-on-a-Chip Systems Using Triply Periodic Minimal Surface Scaffolds',
    journal: 'Advanced Healthcare Materials', vol: 'e02773', IF: 9.6, corr: true, hanbitsa: true, cover: 'Inside Front Cover, AHM 03/2026', coverImg: 'v2/assets/cover-n123.png',
    link: 'https://advanced.onlinelibrary.wiley.com/doi/10.1002/adhm.202502773' },
  { n: 122, y: 2025, authors: 'Kang RH, Shin S, Choi Y, Jang WJ, Park S, Lee MK, Cho HJ, Zhang YS, Kim HJ*, Park BY*, Lee J*',
    title: 'Bioengineered Skin Grafts from Patient-Derived Decellularized Extracellular Matrix and Autologous Cells for Personalized Regenerative',
    journal: 'Advanced Science', vol: 'e11889', IF: 14.1, corr: true, hanbitsa: true, cover: 'Back Cover, Adv Sci 44/2025', coverImg: 'v2/assets/cover-n122.png',
    link: 'https://advanced.onlinelibrary.wiley.com/doi/10.1002/advs.202511889' },
  { n: 121, y: 2025, authors: 'Karmakar M, Kim S, Kim HJ, Huh JW, Jeong DI, Park E, Kim S, Hong EH, Hyeong J, Kim DJ, Choi HK, Lee J, Ko HJ, Lee KB, Kim DD, Cho HJ',
    title: 'Spatiotemporally adjustable hybrid hydrogels interconnected by 2D MXene for combinatorial therapy of infected diabetic wounds',
    journal: 'Chemical Engineering Journal', vol: '522;167327',
    link: 'https://www.sciencedirect.com/science/article/pii/S1385894725081665' },
  { n: 120, y: 2025, authors: 'Shin S, Choi Y, Jang WJ, Ulziituya B, Ha G, Kang R, Park S, Kim M, Zhang YS, Kim HJ*, Lee J*',
    title: 'A Vascularized Tumors-on-a-Chip Model for Studying Tumor-Angiogenesis Interplay, Heterogeneity and Drug Responses',
    journal: 'Materials Today Bio', vol: '32;101741', IF: 8.7, corr: true,
    link: 'https://www.sciencedirect.com/science/article/pii/S259000642500300X' },
  { n: 119, y: 2025, authors: 'Song J, Lee Y, Kim M-S, Ha G, Jang WJ, Batjargal U, Kim YG, Kim HJ*, Lee J*',
    title: 'High throughput drug screening platform utilizing capillary and artery cell layered models based on tumor–vascular cell interactions',
    journal: 'Lab on a chip', vol: '25;2349-2363', IF: 6.1, corr: true, cover: 'Back Cover, Lab on a chip 10/2025', coverImg: 'v2/assets/cover-n119.png',
    link: 'https://pubs.rsc.org/en/content/articlelanding/2025/lc/d4lc00950a' },
  { n: 118, y: 2025, authors: 'Haghniaz R, Aninwene G, Zarei F, Yiu F, Mirmashhouri B, Ramirez J, Darabi A, Tebon P, Montazerian H, Mandal K, Mecwan M, Barros NR, Zhu Y, Kim HJ, Khademhosseini A, Sturm R',
    title: 'Biodegradable, flexible adhesive patch for urinary bladder suture line reinforcement',
    journal: 'Applied Materials Today', vol: '43;102660',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2352940725000794' },
  { n: 117, y: 2025, authors: 'Lee IH, Woo CY, Seo Y, Lee S, Kim HJ*, Lee HW*, Jeon I*',
    title: 'Advanced Facial Mask Using Roll-to-Roll Processed Superhydrophobic Vertically Aligned Carbon Nanotubes for Enhanced Antiviral Effects and Reusability',
    journal: 'SusMat', vol: 'e70001', IF: 18.7, corr: true, hanbitsa: true,
    link: 'https://onlinelibrary.wiley.com/doi/full/10.1002/sus2.70001' },
  { n: 116, y: 2025, authors: 'Lee Y, Song J, Batjargal U, Kim M-S, Lee G, Kim G, Lee T, Kang RH, Kim Y, Kim HJ*, Lee J*',
    title: 'Pseudo-3D Topological Alignments Regulate Mechanotransduction and Maturation of Smooth Muscle Cells',
    journal: 'Advanced Healthcare Materials', vol: '14(4);2402492', IF: 10.0, corr: true, hanbitsa: true, cover: 'Back Cover, AHM 03/2026', coverImg: 'v2/assets/cover-n116.png',
    link: 'https://onlinelibrary.wiley.com/doi/10.1002/adhm.202402492' },
  { n: 115, y: 2025, authors: 'Barros N, Kang R, Kim J, Ermis M, Kim HJ, Dokmeci MR, Lee J',
    title: 'A human skin-on-a-chip platform for microneedling-driven skin cancer treatment',
    journal: 'Materials Today Bio', vol: '30;101399',
    link: 'https://www.sciencedirect.com/science/article/pii/S2590006424004605' },
  // 2024
  { n: 114, y: 2024, authors: 'Lee SJ*, Kim HJ*, Choi EJ, Kim HS, Lee DH, An SH, Min SJ, Ko W-K, Lee JS, Nah HR, Bang JB, Heo M, Heo DN, Do SH, Kwon IK',
    title: 'Immediately injectable modified gelatin and hyaluronic acid-based hydrogel encapsulating nano-hydroxyapatite and human adipose-derived MSCs for use as a bone filler in situ therapy',
    journal: 'Carbohydrate Polymer Technologies and Applications', vol: '100625', IF: 6.2, cofirst: true,
    link: 'https://www.sciencedirect.com/science/article/pii/S2666893924002056' },
  { n: 113, y: 2024, authors: 'Kim HS, Youn YH, Kim HJ, Koo YH, Lee JH, Kwon IK, Do SH',
    title: 'Enhanced Antitumor Efficacy of Oncolytic Vaccinia Virus Therapy Through Keratin-Mediated Delivery in Triple-Negative Breast Cancer',
    journal: 'International Journal of Molecular Sciences', vol: '25(21):11470',
    link: 'https://www.mdpi.com/1422-0067/25/21/11470' },
  { n: 112, y: 2024, authors: 'Kim HS, Kim HJ, Do SH',
    title: 'Early Detection of Chronic Kidney Disease Using Plasma Neutrophil Gelatinase-Associated Lipocalin and Kidney Injury Molecule-1 in Small-Breed Dogs: A Retrospective Pilot Study',
    journal: 'Animals', vol: '14(16):2313',
    link: 'https://www.mdpi.com/2076-2615/14/16/2313' },
  { n: 111, y: 2024, authors: 'Gangrade A, Zehtabi F, Rashad A, Haghniaz R, Falcone N, Mandal K, Khosravi S, Deka S, Yamauchi A, Voskanian L, Kim HJ, Ermis M, Khademhosseini A, Barros NR',
    title: 'Nanobioactive blood-derived shear-thinning biomaterial for tissue engineering applications',
    journal: 'Applied Materials Today', vol: '38:102250',
    link: 'https://www.sciencedirect.com/science/article/pii/S2352940724001951' },
  { n: 110, y: 2024, authors: 'Carvalho BG, Nakayama A, Miwa H, Han SW, Torre LG, Carlo DD, Lee J, Kim HJ*, Khademhosseini A*, Barros NR*',
    title: 'Gelatin methacryloyl granular scaffolds for localized mRNA delivery',
    journal: 'Aggregate', vol: '5(2):e464', IF: 18.8, corr: true,
    link: 'https://onlinelibrary.wiley.com/doi/full/10.1002/agt2.464' },
  { n: 109, y: 2024, authors: 'Falcone N, Ermis M, Gangrade A, Choroomi A, Young P, Mathes TG, Monirizad M, Zehtabi F, Mecwan M, Rodriguez M, Zhu Y, Byun YJ, Khademhosseini A*, Barros NR*, Kim HJ*',
    title: 'Drug-eluting Shear-thinning Hydrogel for the Delivery of Chemo- and Immunotherapeutic agents for the treatment of Hepatocellular Carcinoma',
    journal: 'Advanced Functional Materials', vol: '34(8):2309069', IF: 19.0, corr: true, hanbitsa: true, cover: 'Back Cover, AFM 8/2024', coverImg: 'v2/assets/cover-n109.png',
    link: 'https://onlinelibrary.wiley.com/doi/full/10.1002/adfm.202309069' },
  { n: 108, y: 2024, authors: 'Jeong DI, Kim HJ, Lee SY, Kim S, Huh JW, Ahn JH, Karmakar M, Kim HJ, Lee KJ, Lee J, Ko HJ, Cho HJ',
    title: 'Hydrogel design to overcome thermal resistance and ROS detoxification in photothermal and photodynamic therapy of cancer',
    journal: 'Journal of Controlled Release', vol: '366:142-159',
    link: 'https://www.sciencedirect.com/science/article/pii/S0168365923008210' },
  { n: 107, y: 2024, authors: 'Nottelet B*, Buwalda S*, Nostrum CF, Zhao X, Deng C, Zhong Z, Cheah E, Svirskis D, Trayford C, Rijt S, Kumr R, Kehr NS, Menard-Moyon C, Barros NR, Khademhosseini A, Kim HJ, Vermonden T*',
    title: 'Roadmap on Multifunctional Materials for Drug Delivery',
    journal: 'Journal of Physics: Materials', vol: '7:012502',
    link: 'https://iopscience.iop.org/article/10.1088/2515-7639/ad05e8' },
  { n: 106, y: 2024, authors: 'Barros NR*, Gangrade A, Rashad A, Chen RR, Zehtabi F, Ermis M, Falcone N, Haghniaz R, Khosravi S, Gomez A, Huang S, Mecwan M, Khorsandi D, Lee J, Zhu Y, Li B, Kim HJ, Thankam FG, Khademhosseini A*',
    title: 'Injectable nanoengineered adhesive hydrogel for treating enterocutaneous fistulas',
    journal: 'Acta Biomaterialia', vol: '173:231-246',
    link: 'https://www.sciencedirect.com/science/article/pii/S1742706123006347' },
  // 2023
  { n: 105, y: 2023, authors: 'Zehtabi F, Gangrade A, Tseng K, Haghniaz R, Abasgholizadeh R, Montazerian H, Khorsandi D, Bahari J, Ahari A, Mohaghegh N, Kouchehbaghi NH, Mandal K, Mecwan M, Rashad A, Barros NR, Byun YJ, Ermis M*, Kim HJ*, Khademhosseini A*',
    title: 'Injectable Shear‐Thinning Hydrogels with Sclerosing and Matrix Metalloproteinase Modulatory Properties for the Treatment of Vascular Malformations',
    journal: 'Advanced Functional Materials', vol: '33(51):2305880', IF: 19.0, corr: true, hanbitsa: true,
    link: 'https://onlinelibrary.wiley.com/doi/full/10.1002/adfm.202305880' },
  { n: 104, y: 2023, authors: 'Haghniaz R, Montazerian H, Rabbani A, Baidya A, Usui B, Zhu Y, Tavafoghi M, Wahid F, Kim HJ*, Sheikhi A*, Khademhosseini A*',
    title: 'Injectable, antibacterial, and hemostatic tissue sealant hydrogels',
    journal: 'Advanced Healthcare Materials', vol: '12(31):2301551', IF: 11.092, corr: true, hanbitsa: true, cover: 'Frontispiece, AHM 31/2023', coverImg: 'v2/assets/cover-n104.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adhm.202301551' },
  { n: 103, y: 2023, authors: 'Barros NR*, Wang C, Maity S, Peirsman A, Nasiri R, Herland A, Ermis M, Kawakita S, Carvalho BG, Kouchehbaghi NH, Herculano RD, Tirpakova Z, Dabiri SMH, Tanaka JL, Falcone N, Choroomi A, Chen RR, Huang S, Zisblatt E, Huang Y, Rashad A, Khorsandi D, Gangrade A, Voskanian LK, Zhu Y, Li B, Akbari M, Lee J, Dokmeci MR, Kim HJ*, Khademhosseini A*',
    title: 'Engineered organoids for biomedical applications',
    journal: 'Advanced Drug Delivery Review', vol: '203:115142', IF: 16.1, corr: true, hanbitsa: true,
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0169409X2300457X' },
  { n: 102, y: 2023, authors: 'Barros NR, Darabi MA, Ma X, Diltemiz SE, Ermis M, Najafabasi AH, Nadine S, Banton EA, Mandal K, Abbasgholizadeh R, Falcone N, Mano JF, Nasiri R, Herculano RD, Zhu Y, Ostrovidov S, Lee J, Kim HJ, Hosseini V, Dokmeci MR, Ahadian S, Khademhosseini A',
    title: 'Enhanced Maturation of 3D Bioprinted Skeletal Muscle Tissue Constructs Encapsulating Soluble Factor-Releasing Microparticles',
    journal: 'Macromolecular Bioscience', vol: '23(12):2300276', cover: 'Front Cover, MBS 12/2023', coverImg: 'v2/assets/cover-n102.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/mabi.202300276' },
  { n: 101, y: 2023, authors: 'Falcone N, Ermis M, Tamay DG, Mecwan M, Monirizad M, Mathes TG, Jucaud V, Choroomi A, Barros N, Zhu Y, Vrana NE, Kraatz H-B, Kim HJ, Khademhosseini A',
    title: 'Peptide Hydrogels as Immunomaterials and Their Use in Cancer Immunotherapy Delivery',
    journal: 'Advanced Healthcare Materials', vol: '12(27):2301096',
    link: 'https://onlinelibrary.wiley.com/doi/10.1002/adhm.202301096' },
  { n: 100, y: 2023, authors: 'Barros NR, Gomez A, Ermis M, Falcone N, Haghniaz R, Young P, Gao Y, Aquino A-F, Li S, Niu S, Chen R, Huang S, Zhu Y, Eliahoo P, Khorsandi D, Kim J, Kelber J, Khademhosseini A*, Kim HJ*, Li B*',
    title: 'Gelatin methacryloyl and laponite bioink for 3D bioprinted organotypic tumor modeling',
    journal: 'Biofabrication', vol: '15(4):045005', IF: 11.061, corr: true, hanbitsa: true,
    link: 'https://iopscience.iop.org/article/10.1088/1758-5090/ace0db/meta' },
  { n: 99, y: 2023, authors: 'Kim SH, Lee JS, Lee SJ, Nah H, Min SJ, Moon HJ, Bang JB, Kim HJ, Kim WJ, Kwon IK, Heo DN',
    title: 'Development of a plasma-based 3D printing system for enhancing the biocompatibility of 3D scaffold',
    journal: 'Biofabrication', vol: '15(3):035024',
    link: 'https://iopscience.iop.org/article/10.1088/1758-5090/acdf86/meta' },
  { n: 98, y: 2023, authors: 'Haghniaz R, Gangrade A, Montazerian H, Zarei F, Sen ME, Li Z, Du Y, Khosravi S, Barros NR, Mandal K, Rashad A, Zehtabi F, Li J, Dokmeci MR, Kim HJ, Khademhosseini A, Zhu Y',
    title: 'An All-In-One Transient Theranostic Platform for Intelligent Management of Hemorrhage',
    journal: 'Advanced Science', vol: '10(24):2301406', cover: 'Front Cover, Adv Sci 24/2023', coverImg: 'v2/assets/cover-n98.png',
    link: 'https://onlinelibrary.wiley.com/doi/full/10.1002/advs.202301406' },
  { n: 97, y: 2023, authors: 'Karamikamkar S*, Yalcintas EP, Haghniaz R, Barros NR, Mecwan M, Nasiri R, Davoodi E, Nasrollahi F, Erdem A, Kang H, Lee J, Zhu Y, Ahadian S, Jucaud V, Maleki H, Dokmeci MR, Kim HJ*, Khademhosseini A*',
    title: 'Aerogel-Based Biomaterials for Biomedical Applications: From Fabrication Methods to Disease-Targeting Applications',
    journal: 'Advanced Science', vol: '10(23):2204681', IF: 17.521, corr: true, hanbitsa: true, cover: 'Frontispiece, Adv Sci 23/2023', coverImg: 'v2/assets/cover-n97.png',
    link: 'https://onlinelibrary.wiley.com/doi/10.1002/advs.202204681' },
  { n: 96, y: 2023, authors: 'Ermis M, Falcone N, Barros NR, Mecwan M, Haghniaz R, Choroomi A, Monirizad M, Lee Y, Song J, Cho HJ, Zhu Y, Kang H, Dokmeci MR, Khademhosseini A*, Lee J*, Kim HJ*',
    title: 'Tunable hybrid hydrogels with multicellular spheroids for modeling desmoplastic pancreatic cancer',
    journal: 'Bioactive Materials', vol: '25:360-373', IF: 16.874, corr: true, hanbitsa: true,
    link: 'https://www.sciencedirect.com/science/article/pii/S2452199X23000439' },
  { n: 95, y: 2023, authors: 'Kim S, Hwang C, Jeong DI, Park J, Kim HJ, Lee K, Lee J, Lee S, Cho H',
    title: 'Nanorod/nanodisk-integrated liquid crystalline systems for starvation, chemodynamic, and photothermal therapy of cancer',
    journal: 'Bioengineering & Translational Medicine',
    link: 'https://aiche.onlinelibrary.wiley.com/doi/10.1002/btm2.10470' },
  { n: 94, y: 2023, authors: 'Zhu Y, Haghniaz R, Hartel M, Lei M, Tian X, Garrido P, Wu Z, Hao T, Guan S, Ahadian S, Kim HJ, Jucaud V, Dokmeci MR, Khademhosseini A',
    title: 'Recent Advances in Bioinspired Hydrogels: Materials, Devices, and Biosignal Computing',
    journal: 'ACS Biomaterials Science & Engineering', vol: '9(5):2048-2069', cover: 'Cover, ACS Biomat Sci Eng 9/2023', coverImg: 'v2/assets/cover-n94.png',
    link: 'https://pubs.acs.org/doi/10.1021/acsbiomaterials.1c00741' },
  { n: 93, y: 2023, authors: 'Zhu Y, Li J, Kim J, Li S, Zhao Y, Bahari J, Eliahoo P, Li G, Kawakita S, Haghniaz R, Gao X, Falcone N, Ermis M, Kang H, Liu H, Kim HJ, Tabish T, Yu H, Li B, Akbari M, Emaminejad S, Khademhosseini A',
    title: 'Skin-Interfaced Electronics: A Promising and Intelligent Paradigm for Personalized Healthcare',
    journal: 'Biomaterials', vol: '296:122075',
    link: 'https://www.sciencedirect.com/science/article/pii/S0142961223000832' },
  { n: 92, y: 2023, authors: 'Haghniaz R*, Kim HJ*, Montazerian H, Baidya A, Tavafoghi M, Chen Y, Zhu Y, Karamikamkar S, Sheikhi A, Khademhosseini A',
    title: 'Tissue adhesive hemostatic microneedle arrays for rapid hemorrhage treatment',
    journal: 'Bioactive Materials', vol: '23:314-327', IF: 16.874, cofirst: true, hanbitsa: true, cover: 'Outside Front Cover, Bioactive Mat 23/2023', coverImg: 'v2/assets/cover-n92.png',
    link: 'https://www.sciencedirect.com/science/article/pii/S2452199X22003607' },
  { n: 91, y: 2023, authors: 'Thangam R, Kim SY, Kang N, Hong H, Lee HJ, Lee S, Jeong D, Tag KR, Kim K, Zhu Y, Sun W, Kim HJ, Cho SW, Ahn JP, Jang WY, Kim JS, Paulmurugan R, Khademhosseini A, Kim HK, Kang H',
    title: 'Ligand Coupling and Decoupling Modulates Stem Cell Fate',
    journal: 'Advanced Functional Materials', vol: '33(8)2206673',
    link: 'https://onlinelibrary.wiley.com/doi/full/10.1002/adfm.202206673' },
  { n: 90, y: 2023, authors: 'Lee SH, Baek DJ, Cho WB, Lee NH, Kim KJ, Kim JH, Kim HJ, Kim HH, Kim HJ, Lee SW, Lee SM',
    title: 'Tailoring Luminescent Solar Concentrators for High-Performance Flexible Double-Junction III-V Photovoltaics',
    journal: 'Advanced Functional Materials', vol: '33(6):2210357', cover: 'Inside Front Cover, AFM 06/2023', coverImg: 'v2/assets/cover-n90.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adfm.202210357' },
  { n: 89, y: 2023, authors: 'Lee J, Jeon O, Koh J, Kim HJ, Lee SJ, Zhu Y, Song J, Lee Y, Nasiri R, Lee K, Bandaru P, Cho H, Zhang S, Barros NR, Ahadian S, Kang H, Dokmeci MR, Lee J, Di Carlo D, Alsberg E, Khademhosseini A',
    title: 'Micromechanical property mismatch between pericellular and extracellular matrices regulates stem cell articular and hypertrophic chondrogenesis',
    journal: 'Matter', vol: '6(2):475-492',
    link: 'https://www.sciencedirect.com/science/article/pii/S2590238522006397' },
  { n: 88, y: 2023, authors: 'Zehtabi F, Montazerian H, Haghniaz R, Tseng K, Mohaghegh N, Mandal K, Zamanian B, Dokmeci MR, Akbari M, Najafabadi AH*, Kim HJ*, Khademhosseini A*',
    title: 'Sodium Phytate‐Incorporated Gelatin‐Silicate Nanoplatelet Composites for Enhanced Cohesion and Hemostatic Function of Shear‐Thinning Biomaterials',
    journal: 'Macromolecular Bioscience', vol: '23(1):2200333', IF: 5.859, corr: true, cover: 'Inside Back Cover, MBS 01/2023', coverImg: 'v2/assets/cover-n88.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/mabi.202200333' },
  // 2022
  { n: 87, y: 2022, authors: 'Kim Y, Thangam R, Yoo J, et al.',
    title: 'Photoswitchable Microgels for Dynamic Macrophage Modulation',
    journal: 'Advanced Materials', vol: '34(49):2205498',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adma.202205498' },
  { n: 86, y: 2022, authors: 'An SY, Kim HS, Kim SY, Van SY, Kim HJ, Lee J, Han SW, Kwon IK, Lee C, Do SH, Hwang YS',
    title: 'Keratin-mediated hair growth and its underlying biological mechanism',
    journal: 'Communications Biology', vol: '5(1):1-17',
    link: 'https://www.nature.com/articles/s42003-022-04232-9' },
  { n: 85, y: 2022, authors: 'Lee SY, Park JH, Jeong DI, Hwang CR, Lee J, Lee K, Kim HJ, Cho HJ',
    title: 'Ferrocene and glucose oxidase-installed multifunctional hydrogel reactors for local cancer therapy',
    journal: 'Journal of Controlled Release', vol: '349:617-633',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0168365922004278' },
  { n: 84, y: 2022, authors: 'Kawakita S, Mandal K, Mou L, Mecwan MM, Zhu Y, Li S, Sharma S, Hernandez AL, Nguyen HT, Maity S, Barros NR, Nakayama A, Bandaru P, Ahadian S, Kim HJ, Herculano RD, Holler E, Jucaud V, Dokmeci MR, Khademhosseini A',
    title: 'Organ-On-A-Chip Models of the Blood–Brain Barrier: Recent Advances and Future Prospects',
    journal: 'Small', vol: '18(39):2201401', cover: 'Outside Back Cover, Small 39/2022', coverImg: 'v2/assets/cover-n84.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/smll.202201401' },
  { n: 83, y: 2022, authors: 'Li S, Zhu Y, Haghniaz R, Kawakita S, Guan S, Chen J, Li Z, Mandal K, Bahari J, Shah S, Guo J, Kang H, Sun W, Kim HJ, Jucaud V, Dokmeci MR, Kollbaum P, Lee CH, Khademhosseini A',
    title: 'A Microchambers Containing Contact Lens for the Noninvasive Detection of Tear Exosomes',
    journal: 'Advanced Functional Materials', vol: '32(44):2206620',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adfm.202206620' },
  { n: 82, y: 2022, authors: 'Wu Q*, Qu M*, Kim HJ*, Zhou X, Jiang X, Chen Y, Zhu J, Ren L, Wolter T, Kang H, Xu C, Gu Z, Sun W, Khademhosseini A',
    title: 'A Shear-Thinning Biomaterial-Mediated Immune Checkpoint Blockade',
    journal: 'ACS Applied Materials & Interfaces', vol: '14(31):35309-35318', IF: 10.383, cofirst: true, hanbitsa: true, cover: 'Cover, ACS AMI 31/2022', coverImg: 'v2/assets/cover-n82.png',
    link: 'https://pubs.acs.org/doi/10.1021/acsami.2c06137' },
  { n: 81, y: 2022, authors: 'Bae G, Kim MS, Thangam R, Koo TM, Jang WY, Yoon J, Han S-B, Yang L, Kim SY, Kang N, Min S, Hong H, Fu HE, Ko MJ, Kim D-H, Jeong WK, Kim D-H, Kim T-H, Choi J-W, Lee K-B, Paulmurugan R, Zhu Y, Kim H-J, Lee K, Kim JS, Khademhosseini A, Kim YK, Kang H',
    title: 'Receptor-Level Proximity and Fastening of Ligands Mediates Stem Cell Differentiation',
    journal: 'Advanced Functional Materials', vol: '32(30):2200828',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adfm.202200828' },
  { n: 80, y: 2022, authors: 'Kim HS, Hwang H-J, Kim HJ, Choi Y, Lee D, Jung HH, Do SH',
    title: 'Effect of Decellularized Extracellular Matrix Bioscaffolds Derived From Fibroblasts on Skin Wound Healing and Remodeling',
    journal: 'Frontiers in Bioengineering and Biotechnology', vol: '10:865545',
    link: 'https://www.frontiersin.org/articles/10.3389/fbioe.2022.865545/full' },
  { n: 79, y: 2022, authors: 'Zhu Y#*, Li S#, Li J#, Falcone N, Cui Q, Shah S, Hartel MC, Yu N, Young P, Barros NR, Wu Z, Haghniaz R, Ermis M, Wang C, Kang H, Lee J, Karamikamkar S, Ahadian S, Jucaud V, Dokmeci MR, Kim HJ*, Khademhosseini A*',
    title: 'Lab-on-a-Contact Lens: Recent Advances and Future Opportunities in Diagnostics and Therapeutics',
    journal: 'Advanced Materials', vol: '34(24):2108389', IF: 32.086, corr: true, hanbitsa: true,
    link: 'https://onlinelibrary.wiley.com/doi/10.1002/adma.202108389' },
  { n: 78, y: 2022, authors: 'Wang C*, Jiang X*, Kim HJ*, Zhang S, Zhou X, Chen Y, Ling H, Xue Y, Chen Z, Qu M, Ren L, Zhu J, Libanori A, Zhu Y, Kang H, Ahadian S, Dokmeci MR, Servati P, He X, Gu Z, Sun W, Khademhosseini A',
    title: 'Flexible patch with printable and antibacterial conductive hydrogel electrodes for accelerated wound healing',
    journal: 'Biomaterials', vol: '285:121479', IF: 15.304, cofirst: true, hanbitsa: true,
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0142961222001181' },
  { n: 77, y: 2022, authors: 'Jeong DI, Kim S, Lee SY, Kim H-J, Lee J, Lee K, Cho H-J',
    title: 'Iron sulfate-reinforced hydrogel reactors with glucose deprivation, serial reactive oxygen species generation, ferroptosis induction, and photothermal ablation for cancer therapy',
    journal: 'Chemical Engineering Journal', vol: '438:135584',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1385894722010865' },
  { n: 76, y: 2022, authors: 'Xue Y*, Kim HJ*, Lee J, Liu Y, Hoffman T, Chen Y, Chen Y, Zhou X, Sun W, Zhang S, Cho HJ, Lee JY, Kang H, Ryu WH, Lee CM, Ahadian S, Dokmeci MR, Lei B, Lee K, Khademhosseini A',
    title: 'Co-electrospun Silk Fibroin and Gelatin Methacryloyl Sheet Seeded with Mesenchymal Stem Cells for Tendon Regeneration',
    journal: 'Small', vol: '18(21):2107714', IF: 15.153, cofirst: true, hanbitsa: true,
    link: 'https://onlinelibrary.wiley.com/doi/10.1002/smll.202107714' },
  { n: 75, y: 2022, authors: 'Kim HS, Hwang H-J, Kim HJ, Do SH',
    title: 'Case report: Articular gout in four dogs and one cat',
    journal: 'Frontiers in Veterinary Science', vol: '9:752774',
    link: 'https://www.frontiersin.org/articles/10.3389/fvets.2022.752774/full' },
  { n: 74, y: 2022, authors: 'Kiaee G, Dimitrakakis N, Sharifzadeh S, Kim HJ, Avery RK, Moghaddam KM, Haghiniaz R, Yalcintas EP, Barros NR, Karamikamkar S, Libanori A, Khademhosseini A, Khoshakhlagh P',
    title: 'Laponite‐based Nanomaterials For Drug Delivery',
    journal: 'Advanced Healthcare Materials', vol: '11(7):2102054',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adhm.202102054' },
  { n: 73, y: 2022, authors: 'Zhu Y#*, Hartel MC#, Yu N, Garrido PR, Kim S, Lee J, Bandaru P, Guan S, Lin H, Emaminejad S, Barros NR, Ahadian S, Kim HJ, Sun W, Jucaud V, Dokmeci MR, Weiss PS, Yan R*, Khademhosseini A*',
    title: 'Epidermis-inspired Wearable Piezoresistive Pressure Sensors using Reduced Graphene Oxide Self-Wrapped Copper Nanowire Networks',
    journal: 'Small Methods', vol: '6(1):2100900',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/smtd.202100900' },
  { n: 72, y: 2022, authors: 'Lee J, Wang Y, Xue C, Chen Y, Qu M, Thakor J, Zhou X, Barros NR, Falcone N, Young P, Floor WD, Lee K, Zhu Y, Cho H-J, Sun W, Zhao B, Ahadian S, Jucaud V, Dokmeci MR, Khademhosseini A*, Kim HJ*',
    title: 'pH-responsive Doxorubicin Delivery using Shear-Thinning Biomaterials for Localized Melanoma Treatment',
    journal: 'Nanoscale', vol: '14(2):350-360', IF: 8.307, corr: true, cover: 'Inside Back cover, Nanoscale 2/2022', coverImg: 'v2/assets/cover-n72.png',
    link: 'https://pubs.rsc.org/en/content/articlelanding/2022/nr/d1nr05738c' },
  { n: 71, y: 2022, authors: 'Baghdasarian S, Saleh B, Baidya A, Kim HJ, Ghovvati M, Sani ES, Haghniaz R, Madhu S, Kanelli M, Noshadi I, Annabi N',
    title: 'Engineering a naturally derived hemostatic sealant for sealing internal organs',
    journal: 'Materials Today Bio', vol: '13:100199',
    link: 'https://www.sciencedirect.com/science/article/pii/S2590006421001071' },
  // 2021
  { n: 70, y: 2021, authors: 'Lee J, Ung A, Kim HJ, Lee K, Cho H, Bandaru P, Ahadian S, Dokmeci MR, Khademhosseini A',
    title: 'Engineering liver microtissues to study the fusion of HepG2 with mesenchymal stem cells and invasive potential of fused cells',
    journal: 'Biofabrication', vol: '14(1):014104',
    link: 'https://iopscience.iop.org/article/10.1088/1758-5090/ac36de' },
  { n: 69, y: 2022, authors: 'Kim KH, Shin JH, Kim HS, Kim HJ, Kim JH, Do SH, Kim HY',
    title: 'Multiple undifferentiated pleomorphic sarcoma (malignant fibrous histiocytoma) with extradural involvement in a 7-year-old Labrador retriever',
    journal: 'Veterinary Sciences', vol: '9(1):3',
    link: 'https://www.mdpi.com/2306-7381/9/1/3' },
  { n: 68, y: 2021, authors: 'Kim HS, Kim HJ, Hwang HH, Ahn JH, Do SH',
    title: 'Immunophenotyping of an Unusual Mixed-Type Extraskeletal Osteosarcoma in a Dog',
    journal: 'Veterinary Sciences', vol: '8(12): 307',
    link: 'https://www.mdpi.com/2306-7381/8/12/307' },
  { n: 67, y: 2021, authors: 'Nasrollahi F, Haghniaz R, Davoodi E, Zhu Y, Darabi A, Hosseini V, Karamikamkar S, Lee J, Diltemiz SE, Montazerian H, Mahmoodi M, Sangabathuni S, Jucaud V, Kim HJ, Ahadian S, Khademhosseini A',
    title: 'Micro and Nanoscale Technologies for Diagnosis of Viral Infections',
    journal: 'Small', vol: '17(45):2100692',
    link: 'https://onlinelibrary.wiley.com/doi/full/10.1002/smll.202100692' },
  { n: 66, y: 2021, authors: 'Barros NR, Chen Y, Hosseini V, Wang W, Nasiri R, Mahmoodi M, Yalcintas EP, Haghniaz R, Mecwan MM, Karamikamkar S, Dai W, Sarabi SA, Falcone N, Young P, Sun W, Zhang S, Lee J, Lee K, Ahadian S, Dokmeci MR, Khademhosseini A*, Kim HJ*',
    title: 'Recent developments in mussel-inspired materials for biomedical applications',
    journal: 'Biomaterials Science', vol: '9(20):6653-6672', IF: 7.590, corr: true, cover: 'Inside Back cover, Biomat Sci 20/2021', coverImg: 'v2/assets/cover-n66.png',
    link: 'https://pubs.rsc.org/en/content/articlelanding/2021/bm/d1bm01126j' },
  { n: 65, y: 2021, authors: 'Zhu Y, Mandal K, Hernandez AL, Kawakita S, Huang W, Bandaru P, Ahadian S, Kim HJ, Jucaud V, Dokmeci MR, Khademhosseini A',
    title: 'State of the art in integrated biosensors for organ-on-a-chip applications',
    journal: 'Current Opinion in Biomedical Engineering', vol: '19:100309',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2468451121000490' },
  { n: 64, y: 2021, authors: 'Kim HJ, Choi EJ, Choi EW, Kim JG, Cho GS, Shin JH, Kim H, Do SH, Park BJ',
    title: 'Non-thermal plasma promotes hair growth by improving the inter-follicular macroenvironment',
    journal: 'RSC Advances', vol: '11(45):7880-27896', IF: 4.036, first: true,
    link: 'https://pubs.rsc.org/en/content/articlelanding/2021/ra/d1ra04625j' },
  { n: 63, y: 2021, authors: 'Hwang CR, Lee SY, Kim HJ, Lee KJ, Lee JM, Kim DD, Cho HJ',
    title: 'Polypseudorotaxane and polydopamine linkage-based hyaluronic acid hydrogel network with a single syringe injection for sustained drug delivery',
    journal: 'Carbohydrate Polymers', vol: '266:118104',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0144861721004914' },
  { n: 62, y: 2021, authors: 'Barros NR, Kim HJ, Goudie M, Lee KJ, Bandaru P, Banton EA, Sarikhani E, Sun W, Zhang S, Cho HJ, Hartel MC, Ostrovidov S, Ahadian Hussain S, Ashammakhi N, Dokmeci MR, Herculano RD, Lee JM, Khademhosseini A',
    title: 'Biofabrication of endothelial cell, dermal fibroblast, and multilayered keratinocyte layers for skin tissue engineering',
    journal: 'Biofabrication', vol: '13:035030',
    link: 'https://iopscience.iop.org/article/10.1088/1758-5090/aba503' },
  { n: 61, y: 2021, authors: 'Roberts DG, Goudie M, Kim A, Kim HJ, Khademhosseini A, McWilliams JP',
    title: 'Novel dual-lumen drainage catheter to enhance the active evacuation of complex fluid collections',
    journal: 'Journal of Vascular and Interventional Radiology', vol: '32(6):882-889',
    link: 'https://linkinghub.elsevier.com/retrieve/pii/S1051-0443%2821%2900797-1' },
  { n: 60, y: 2021, authors: 'Cho H*, Kim HJ*, Lee K, Nasiri R, Hoffman T, Bandaru P, Ung A, Tebon P, Hartel M, Sun W, Zhang S, Ahadian S, Ashammakhi N, Dokmeci MR, Lee J, Khademhosseini A',
    title: 'Bioengineered Multicellular Liver Microtissues for Modeling Advanced Hepatic Fibrosis Driven Through Non-Alcoholic Fatty Liver Disease',
    journal: 'Small', vol: '17(14):2007425', IF: 15.153, cofirst: true, hanbitsa: true, cover: 'Outside Front cover, Small 14/2021', coverImg: 'v2/assets/cover-n60.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/smll.202007425' },
  { n: 59, y: 2021, authors: 'Kim HS, Kim HJ, Hwang HJ, Oh S, Do SH',
    title: "Aggressive behaviour of Hodgkin's-like lymphoma in a domestic ferret",
    journal: 'Veterinarni Medicina', vol: '66(05):225-232',
    link: 'https://www.agriculturejournals.cz/web/vetmed.htm?type=article&id=115_2020-VETMED' },
  { n: 58, y: 2021, authors: 'Jiang X, Ren L, Tebon P, Wang C, Zhou X, Qu M, Zhu J, Ling H, Zhang S, Xue Y, Wu Q, Bandaru P, Lee JM, Kim HJ, Ahadian S, Ashammakhi N, Dokmeci MR, Wu J, Gu Z, Sun W*, Khademhosseini A*',
    title: 'Cancer-on-a-chip for modeling immune checkpoint inhibitor and tumor interactions',
    journal: 'Small', vol: '17(7):2004282',
    link: 'https://onlinelibrary.wiley.com/doi/10.1002/smll.202004282' },
  { n: 57, y: 2021, authors: 'Haghiniaz R, Rabbani A, Vajhadin F, Khan T, Kousar R, Khan AR, Montazerian H, Iqbal J, Libanori A, Kim HJ*, Wahid F*',
    title: 'Anti-bacterial and wound healing-promoting effects of zinc ferrite nanoparticles',
    journal: 'Journal of Nanobiotechnology', vol: '19(1):1-15', IF: 9.429, corr: true, hanbitsa: 'top-cited',
    link: 'https://jnanobiotechnology.biomedcentral.com/articles/10.1186/s12951-021-00776-w' },
  { n: 56, y: 2021, authors: 'Lee SY, Yang M, Seo J, Jeong DI, Hwang C, Kim HJ, Lee J, Lee K, Park J, Cho HJ',
    title: 'Serially pH-Modulated Hydrogels Based on Boronate Ester and Polydopamine Linkages for Local Cancer Therapy',
    journal: 'ACS Applied Materials & Interfaces', vol: '13(2):2189-2203',
    link: 'https://pubs.acs.org/doi/10.1021/acsami.0c16199' },
  { n: 55, y: 2021, authors: 'Albadawi H, Altum I, Hu J, Zhang Z, Panda A, Kim HJ, Khademhosseini A, Oklu R',
    title: 'Nanocomposite Hydrogel with Tantalum Microparticles for Rapid Endovascular Hemostasis',
    journal: 'Advanced Science', vol: '8(1):2003327', cover: 'Inside Front Cover, Adv Sci 1/2021', coverImg: 'v2/assets/cover-n55.png',
    link: 'https://onlinelibrary.wiley.com/doi/full/10.1002/advs.202003327' },
  // 2020
  { n: 54, y: 2020, authors: 'Li Z, Zhang S, Chen Y, et al.',
    title: 'Gelatin methacryloyl-based tactile sensors for medical wearables',
    journal: 'Advanced Functional Materials', vol: '30(49):2003601', cover: 'Inside Back Cover, AFM 49/2020', coverImg: 'v2/assets/cover-n54.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adfm.202003601' },
  { n: 53, y: 2020, authors: 'Seo JH, Lee SY, Kim S, et al.',
    title: 'Monopotassium phosphate-reinforced in situ forming injectable hyaluronic acid hydrogels for subcutaneous injection',
    journal: 'International Journal of Biological Macromolecules', vol: '163:2134-2144',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0141813020344500' },
  { n: 52, y: 2020, authors: 'Xue Y, Lee J, Kim HJ, Cho HJ, Zhou X, Liu Y, Tebon P, Qu M, Ling H, Jiang X, Li Z, Zhang S, Sun W, Ahadian S, Dokmeci MR, Lee K, Khademhosseini A',
    title: 'Rhodamine Conjugated Gelatin Methacryloyl Nanoparticles for Stable Cell Imaging',
    journal: 'ACS Applied Bio Materials', vol: '3(10):6908-6918',
    link: 'https://pubs.acs.org/doi/10.1021/acsabm.0c00802' },
  { n: 51, y: 2020, authors: 'Ren L, Zhou X, Nasiri R, et al.',
    title: 'Combined Effects of Electric Stimulation and Microgrooves in Cardiac Tissue-on-a Chip for Drug Screening',
    journal: 'Small Methods', vol: '4(10):20200438',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/smtd.202000438' },
  { n: 50, y: 2020, authors: 'Hassanpour S*, Kim HJ*, Saadati A, et al.',
    title: 'Thrombolytic agents: Nanocarriers in controlled release',
    journal: 'Small', vol: '16(40):2001647', IF: 15.153, cofirst: true, hanbitsa: true,
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/smll.202001647' },
  { n: 49, y: 2020, authors: 'Kim HJ*, Lee HR*, Kim HS, Do SH',
    title: 'Hypoxia Helps Maintain Nucleus Pulposus Homeostasis by Balancing Autophagy and Apoptosis',
    journal: 'Oxidative Medicine and Cellular Longevity', vol: '2020:5915481', IF: 7.310, cofirst: true,
    link: 'https://www.hindawi.com/journals/omcl/2020/5915481/' },
  { n: 48, y: 2020, authors: 'Qu M, Kim HJ, Zhou X, Wang C, Jiang X, Zhu J, Xue Y, Tebon P, Sarabi S, Ahadian S, Dokmeci MR, Zhu S, Gu Zhen, Sun W, Khademhosseini A',
    title: 'Biodegradable microneedle patch for transdermal gene delivery',
    journal: 'Nanoscale', vol: '12(32):16724-16729',
    link: 'https://pubs.rsc.org/en/content/articlelanding/2020/nr/d0nr02759f' },
  { n: 47, y: 2020, authors: 'Xue C, Xie H, Eichenbaum J, et al., Kim HJ*, Khademhosseini A*',
    title: 'Synthesis of injectable shear-thinning biomaterials of various compositions of gelatin and synthetic silicate nanoplatelet',
    journal: 'Biotechnology Journal', vol: '15(8):e1900456', IF: 5.726, corr: true, cover: 'Outside Front cover, BTJ 8/2020', coverImg: 'v2/assets/cover-n47.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/biot.201900456' },
  { n: 46, y: 2020, authors: 'Kim HJ, Hopfield J, Brogan L, Khademhosseini A',
    title: 'Terasaki Institute: Innovating Personalized Health through Convergent Science and Bioengineering',
    journal: 'Matter [Opinion]', vol: '2:324-326', IF: 19.967, first: true,
    link: 'https://www.sciencedirect.com/science/article/pii/S2590238520303763' },
  { n: 45, y: 2020, authors: 'Bandaru P, Cefaloni G, Vajhadin F, et al.',
    title: 'Mechanical Cues Regulating Proangiogenic Potential of Human Mesenchymal Stem Cells through YAP‐Mediated Mechanosensing',
    journal: 'Small', vol: '16(25):2001837', cover: 'Outside Back Cover, Small 25/2020', coverImg: 'v2/assets/cover-n45.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/smll.202001837' },
  { n: 44, y: 2020, authors: 'Zhou X, Luo Z, Baidya A, Kim HJ, et al.',
    title: 'Biodegradable β-cyclodextrin conjugated gelatin methacryloyl microneedle for delivery of water-insoluble drug',
    journal: 'Advanced Healthcare Materials', vol: '9(11):2000527',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adhm.202000527' },
  { n: 43, y: 2020, authors: 'Lee KJ, Xue Y, Lee JM, Kim HJ, et al.',
    title: 'A Patch of Detachable Hybrid Microneedle Depot for Localized Delivery of Mesenchymal Stem Cells in Regeneration Therapy',
    journal: 'Advanced Functional Materials', vol: '30(23):202000086', cover: 'Outside Front Cover, AFM 23/2020', coverImg: 'v2/assets/cover-n43.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adfm.202000086' },
  { n: 42, y: 2020, authors: 'Lee JM, Jeon OJ, Kong M, Abdeen AA, Shin J, Lee HN, Lee YB, Sun W, Bandaru P, Alt DS, Lee KJ, Kim HJ, Lee SJ, Shin SR, Alsberg E, Khademhosseini A',
    title: 'Combinatorial screening of biochemical and physical signals for phenotypic regulation of stem cell–based cartilage tissue engineering',
    journal: 'Science Advances', vol: '6(21):eaaz5913',
    link: 'https://www.science.org/doi/10.1126/sciadv.aaz5913' },
  { n: 41, y: 2020, authors: 'Zhu J, Zhou X, Kim HJ, et al.',
    title: 'Gelatin methacryloyl microneedle patches for minimally-invasive extraction of skin interstitial fluid',
    journal: 'Small', vol: '16(16):1905910', cover: 'Inside Front Cover, Small 16/2020', coverImg: 'v2/assets/cover-n41.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/smll.201905910' },
  { n: 40, y: 2020, authors: 'Heo DN*, Kim HJ*, Lee DH*, Kim HS, Lee SJ, Lee HR, Kwon IK, Do SH',
    title: 'Comparison of polysaccharides in articular cartilage regeneration associated with chondrogenic and autophagy-related gene expression',
    journal: 'International Journal of Biological Macromolecules', vol: '146:922-930', IF: 8.025, cofirst: true,
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0141813019318872' },
  { n: 39, y: 2020, authors: 'Lee KJ, Goudie MJ, Tebon P, Sun W, Luo Z, Lee JM, Zhang S, Fetah K, Kim HJ, Xue Y, Mohammad AD, Ahadian S, Sarikhani E, Ryu WH, Gu Z, Weiss P, Dokmeci MR, Ashammakhi N, Khademhosseini A',
    title: 'Non-transdermal Microneedles for Advanced Drug Delivery',
    journal: 'Advanced Drug Delivery Review', vol: '165-166:41-59',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0169409X19302406' },
  { n: 38, y: 2020, authors: 'Zhang S, Chen Y, Liu H, Wang Z, Ling H, Wang C, Ni J, Saltik B, Wang X, Kim HJ, Baidya A, Ahadian S, Ashammakhi N, Dokmeci MR, Travas-Sejdic J, Khademhosseini A',
    title: 'Room-temperature Formed PEDOT:PSS Hydrogels Enable Injectable, Soft, and Healable Organic Bioelectronics',
    journal: 'Advanced Materials', vol: '32(1):201904752', cover: 'Frontispiece, Adv Mater 32/2020', coverImg: 'v2/assets/cover-n38.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adma.201904752' },
  // 2019
  { n: 37, y: 2019, authors: 'Suurmond CE, Lasli S, van den Dolder FW, Ung A, Kim HJ, Bandaru P, Lee KJ, Cho HJ Ahadian S, Ashammakhi N, Lee JM, Khademhosseini A',
    title: 'In Vitro Human Liver Model of Nonalcoholic Steatohepatitis by Coculturing Hepatocytes, Endothelial Cells, and Kupffer Cells',
    journal: 'Advanced Healthcare Materials', vol: '8(24):201901379', cover: 'Outside Front Cover, AHM 24/2019', coverImg: 'v2/assets/cover-n37.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adhm.201901379' },
  { n: 36, y: 2019, authors: 'Asahmmakhi N, Kim HJ, Ehsanipour A, Bierman RD, Kaarela O, Xue C, Seidlits SK, Khademhosseini A',
    title: 'Regenerative Therapy for Spinal Cord Injury',
    journal: 'Tissue Engineering, Part B: Reviews', vol: '25(6):471-491', cover: 'Outside Front Cover, Tissue Eng B 6/2019', coverImg: 'v2/assets/cover-n36.png',
    link: 'https://www.liebertpub.com/doi/10.1089/ten.teb.2019.0182' },
  { n: 35, y: 2019, authors: 'Lee SJ*, Kim HJ*, Heo M, Lee HR, Choi EJ, Kim HS, Lee DH, Nah HR, Reis RL, Bang JB, Hwang YS, Do SH, Kwon IK',
    title: 'In vitro and In vivo Assessments of an Optimal Polyblend Composition of Polycaprolactone/Gelatin Electrospun Nanofibrous Scaffolds for Tendon Tissue Engineering Application',
    journal: 'Journal of Industrial and Engineering Chemistry', vol: '76:173-180', IF: 6.760, cofirst: true,
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1226086X19301236' },
  { n: 34, y: 2019, authors: 'Ni J, Ling H, Zhang S, Wang W, Peng Z, Benyshek C, Zan R, Miri AK, Li Z, Zhang X, Lee J, Lee KJ, Kim HJ, Tebon P, Hoffman T, Dokmeci MR, Ashammakhi N, Li X, Khademhosseini A',
    title: 'Three-Dimensional Printing of Metals for Biomedical Applications',
    journal: 'Materials Today Bio', vol: '3:100024',
    link: 'https://www.sciencedirect.com/science/article/pii/S259000641930050X' },
  { n: 33, y: 2019, authors: 'Lasli S, Kim HJ, Lee KJ, Suurmond CE, Goudie M, Bandaru P, Sun W, Zhang S, Zhang N, Ahadian S, Dokmeci MR, Lee J, Khademhosseini A',
    title: 'A Human Liver-on-a-Chip Platform for Modeling Nonalcoholic Fatty Liver Disease',
    journal: 'Advanced Biosystems', vol: '3(8):1900104', cover: 'Outside Back Cover, Adv Biosys 8/2019', coverImg: 'v2/assets/cover-n33.png',
    link: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/adbi.201900104' },
  { n: 32, y: 2019, authors: 'Kim HJ, Choi EJ, Kim HS, Choi CW, Kim SL, Seo WD, Do SH',
    title: 'Soyasaponin Ab alleviates postmenopausal obesity through browning of white adipose tissue',
    journal: 'Journal of Functional Foods', vol: '57:453-464', IF: 5.223, first: true,
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S175646461930177X' },
  { n: 31, y: 2019, authors: 'Lee DH, Choi EJ, Lee SE, Kang KL, Moon HJ, Kim HJ, Youn YH, Heo DN, Lee SJ, Nah HR, Hwang YS, Lee YH, Seong JM, Do SH, Kwon IK',
    title: 'Injectable biodegradable gelatin-methacrylate/β‐tricalcium phosphate composite for the repair of bone defects',
    journal: 'Chemical Engineering Journal', vol: '365:30-39',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1385894719302372' },
  { n: 30, y: 2019, authors: 'Kim HJ, Han MA, Shin JY, Jeon JH, Lee SJ, Kim HJ, Choi EJ, Do SH, Yang VC, He H, Yang YI',
    title: 'Intra-articular delivery of synovium-resident mesenchymal stem cells via BMP-7-loaded fibrous PLGA scaffolds for cartilage repair',
    journal: 'Journal of Controlled Release', vol: '302:169-180',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0168365919301944' },
  { n: 29, y: 2019, authors: 'Sun WJ, Luo ZM, Lee JM, Kim HJ, Lee KJ, Feng YD, Khademhosseini A',
    title: 'Organ-on-a-Chip for Cancer and Immune Organs Modeling',
    journal: 'Advanced Healthcare Materials', vol: '8(4):e1801363', cover: 'Outside Back Cover, AHM 4/2019', coverImg: 'v2/assets/cover-n29.png',
    link: 'https://onlinelibrary.wiley.com/doi/10.1002/adhm.201900754' },
  { n: 28, y: 2019, authors: 'Kim HJ, Choi EJ, Kim HS, Choi CW, Seo WD, Do SH',
    title: 'Germinated Soy Germ Extract ameliorates obesity through beige fat activation',
    journal: 'Food & Function', vol: '10(2):836-848', IF: 6.317, first: true,
    link: 'https://pubs.rsc.org/en/content/articlelanding/2019/fo/c8fo02252f' },
  // 2018 & earlier (partial — from fetched data)
  { n: 27, y: 2018, authors: 'Yun YJ, Kim HJ, Lee DW, Um SW, Chun HJ',
    title: 'Polydopamine-mediated surface modifications of poly l-lactic acid with hydroxyapatite, heparin and BMP-2 and their effects on osseointegration',
    journal: 'Journal of Industrial and Engineering Chemistry', vol: '67:244-254',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1226086X18303265' },
  { n: 26, y: 2018, authors: 'Jung KH, Park JA, Kim JY, Kim MH, Oh SY, Kim HK, Choi EJ, Kim HJ, Do SH, Lee KC, Kim KM, Lee YJ, Chang YM',
    title: 'Image-Guided Neutron Capture Therapy Using the Gd-DO3A-BTA Complex as a New Combinatorial Treatment Approach',
    journal: 'Contrast Media & Molecular Imaging', vol: '3727109',
    link: 'https://www.hindawi.com/journals/cmmi/2018/3727109/' },
  { n: 25, y: 2018, authors: 'Koo YW, Choi EJ, Lee JY, Kim HJ, Kim GH, Do SH',
    title: '3D printed cell-laden collagen and hybrid scaffolds for in vivo articular cartilage tissue regeneration',
    journal: 'Journal of Industrial and Engineering Chemistry', vol: '66:343-355',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1226086X18302788' },
  { n: 24, y: 2018, authors: 'Choi KS*, Kim HJ*, Do SH, Hwang SJ, Yi HJ',
    title: 'Neuroprotective effects of hydrogen inhalation in an experimental rat intracerebral hemorrhage model',
    journal: 'Brain Research Bulletin', vol: '142:122-128', IF: 3.715, cofirst: true,
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S036192301730566X' },
  { n: 23, y: 2018, authors: 'Choi CW, Choi SW, Kim HJ, Lee KS, Kim SH, Kim SL, Do SH, Seo WD',
    title: 'Germinated soy germ with increased soyasaponin Ab improves BMP-2-induced bone formation and protects against in vivo bone loss in osteoporosis',
    journal: 'Scientific Reports', vol: '8:12970',
    link: 'https://www.nature.com/articles/s41598-018-31118-w' },
  { n: 22, y: 2018, authors: 'Yoo SJ, Kim HJ, Kim HJ, Lee SY, Kim SH, Yoo YS, Hwang JY, Do SH, Kim HY, Kim DH',
    title: 'Subcutaneous Fibrosarcoma in the Occipital Region with Nuchal Crest Adhesion in a 5-month-old Dog',
    journal: 'Journal of Veterinary Clinics', vol: '35(2):63-66',
    link: 'https://www.e-sciencecentral.org/articles/?scid=1136574' },
  // 2013-2017
  { n: 21, y: 2017, authors: 'Kim HJ, Heo DN, Lee YJ, Lee SJ, Kang JY, Lee SH, Kwon IK, Do SH',
    title: 'Biological assessments of multifunctional hydrogel-decorated implantable neural cuff electrode for clinical neurology application',
    journal: 'Scientific Reports', vol: '7(1):5245', IF: 4.996, first: true,
    link: 'https://www.nature.com/articles/s41598-017-05147-w' },
  { n: 20, y: 2017, authors: 'Yoo S, Kim J, Myung HW, Woo S, Chung DJ, Lee AJ, Kim HJ, Do SH, Kim HY',
    title: 'Primary intrapelvic hemangiosarcoma in a dog',
    journal: 'Journal of Veterinary Medical Science', vol: '79(1):192-196',
    link: 'https://www.jstage.jst.go.jp/article/jvms/79/1/79_16-0358/_article' },
  { n: 19, y: 2017, authors: 'Lee YJ*, Kim HJ*, Kang JY, Do SH, Lee SH',
    title: 'Biofunctionalization of Nerve Interface via Biocompatible Polymer-Roughened Pt Black on Cuff Electrode for Chronic Recording',
    journal: 'Advanced Healthcare Materials', vol: '6(6):1601022', IF: 11.092, cofirst: true,
    link: 'https://onlinelibrary.wiley.com/doi/10.1002/adhm.201601022' },
  { n: 18, y: 2017, authors: 'Heo DN, Kim HJ, Lee YJ, Heo M, Lee SJ, Lee D, Do SH, Lee SH, Kwon IK',
    title: 'Flexible and Highly Biocompatible Nanofiber-Based Electrodes for Neural Surface Interfacing',
    journal: 'ACS Nano', vol: '11(3):2961-2971', cover: 'Outside Front Cover, ACS Nano 3/2017', coverImg: 'v2/assets/cover-n18.png',
    link: 'https://pubs.acs.org/doi/10.1021/acsnano.6b08390' },
  { n: 17, y: 2017, authors: 'Kim DH, Kim HJ, Choi EJ, Sah KW, Lee HS, Kwon KB, Kim HY, Do SH',
    title: 'Extranodal marginal zone B-cell lymphomas of the bilateral third eyelids in a dog',
    journal: 'Veterinarni Medicina', vol: '6:351-355',
    link: 'https://vetmed.agriculturejournals.cz/artkey/vet-201706-0009.php' },
  { n: 16, y: 2016, authors: 'Lee YJ, Kim HJ, Do SH, Kang JY, Lee SH',
    title: 'Characterization of Nerve-Cuff Electrode Interface for Biocompatible and Chronic Stimulating Application',
    journal: 'Sensors and Actuators, B', vol: '237:924-934',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0925400516310346' },
  { n: 15, y: 2016, authors: 'Lee D, Heo DN, Kim HJ, Ko WK, Lee SJ, Heo M, Bang JB, Lee JB, Hwang DS, Do SH, Kwon IK',
    title: 'Inhibition of Osteoclast Differentiation and Bone Resorption by Bisphosphonate-conjugated Gold Nanoparticles',
    journal: 'Scientific Reports', vol: '6:27336',
    link: 'https://www.nature.com/articles/srep27336' },
  { n: 14, y: 2016, authors: 'Heo DN, Song SJ, Kim HJ, Lee YJ, Ko WK, Lee SJ, Lee D, Park SJ, Zhang LG, Kang JY, Do SH, Lee SH, Kwon IK',
    title: 'Multifunctional hydrogel coatings on the surface of neural cuff electrode for improving electrode-nerve tissue interfaces',
    journal: 'Acta Biomaterialia', vol: '39:25-33',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1742706116302045' },
  { n: 13, y: 2016, authors: 'Lee HR, Shon OJ, Park SI, Kim HJ, Kim S, Ahn MW, Do SH',
    title: 'Platelet-Rich Plasma Increases the Levels of Catabolic Molecules and Cellular Dedifferentiation in the Meniscus of a Rabbit Model',
    journal: 'International Journal of Molecular Science', vol: '17(1):120',
    link: 'https://www.mdpi.com/1422-0067/17/1/120' },
  { n: 12, y: 2016, authors: 'Myung HW, Lee AJ, Kim JY, Kim JH, Eom KD, Kim HJ, Do SH, Kim HY, Chung DJ',
    title: 'Secondary abdominal pregnancy with foetal mummification diagnosed using computed tomography in a dog: a case report',
    journal: 'Veterinarni Medicina', vol: '1:51-55',
    link: 'https://vetmed.agriculturejournals.cz/artkey/vet-201601-0008.php' },
  { n: 11, y: 2015, authors: 'Kim HJ, Lee HR, Park YS, Kyung SG, Do SH',
    title: 'Assessment of the accuracy and precision of the i-Smart 30 VET Electrolyte Analyzer in dogs, cats, cattle and pigs',
    journal: 'Veterinary Clinical Pathology', vol: '44(3):410-9', IF: 1.333, first: true,
    link: 'https://onlinelibrary.wiley.com/doi/10.1111/vcp.12270' },
  { n: 10, y: 2015, authors: 'Han D*, Kim HJ*, Choi HY, Kim B, Yang G, Han J, Dayem AA, Lee HR, Kim JH, Lee KM, Jeong KS, Do SH, Cho SG',
    title: "3,2'-Dihydroxyflavone-Treated Pluripotent Stem Cells Show Enhanced Proliferation, Pluripotency Marker Expression, and Neuroprotective Properties",
    journal: 'Cell Transplantation', vol: '24(8):1511-32', IF: 4.139, cofirst: true,
    link: 'https://journals.sagepub.com/doi/10.3727/096368914X683494' },
  { n: 9, y: 2015, authors: 'Kim HJ, Choi EJ, Lee HR, Park GJ, Yun ES, Kim JH, Do SH',
    title: 'Spindle cell lipoma in the gingiva of a dog: a case report',
    journal: 'Veterinarni Medicina', vol: '60(6):336-340', IF: 0.746, first: true,
    link: 'https://vetmed.agriculturejournals.cz/artkey/vet-201506-0006.php' },
  { n: 8, y: 2015, authors: 'Park HA, Jeong CW, Kim GS, Kim HJ, Do SH, Park HM',
    title: 'Primary renal fibrosarcoma with local invasion into the mesenteric membrane of a mongrel dog',
    journal: 'Korean Journal of Veterinary Research', vol: '55(1):65-69',
    link: 'https://www.koreascience.or.kr/article/JAKO201511758119096.page' },
  { n: 7, y: 2015, authors: 'Kim HJ, Choi EJ, Lee HR, Kwon BT, Do SH',
    title: 'Cutaneous extrarenal rhabdoid tumor in a dog: a case report',
    journal: 'Veterinarni Medicina', vol: '60(2):115-119', IF: 0.746, first: true,
    link: 'https://vetmed.agriculturejournals.cz/artkey/vet-201502-0007.php' },
  { n: 6, y: 2014, authors: 'Heo DN, Ko WK, Moon HJ, Kim HJ, Lee SJ, Lee JB, Bae MS, Yi JK, Hwang YS, Bang JB, Kim EC, Do SH, Kwon IK',
    title: 'Inhibition of osteoclast differentiation by gold nanoparticles functionalized with cyclodextrin curcumin complexes',
    journal: 'ACS Nano', vol: '8(12):12049-12062',
    link: 'https://pubs.acs.org/doi/10.1021/nn504329u' },
  { n: 5, y: 2014, authors: 'Lim HK, Kim HJ, Lee HR, Han S, Do SH',
    title: 'Angiokeratoma with lysosomal dilatation in keratinocytes in a dog: a case report',
    journal: 'Veterinarni Medicina', vol: '59(9):453-456',
    link: 'https://vetmed.agriculturejournals.cz/artkey/vet-201409-0006.php' },
  { n: 4, y: 2014, authors: 'Kim HJ, Lee HR, Kim JH, Do SH',
    title: 'Estrogen receptors α and β in a pure uterine lipoma in a dog',
    journal: 'Pakistan Veterinary Journal', vol: '34(4):563-565', IF: 1.803, first: true,
    link: 'http://pvj.com.pk/pdf-files/34_4/563-565.pdf' },
  { n: 3, y: 2013, authors: 'Lee HR, Kim HJ, Ko JS, Choi YS, Ahn MW, Kim S, Do SH',
    title: 'Comparative characteristics of porous bioceramics for an osteogenic response in vitro and in vivo',
    journal: 'PLoS One', vol: '8(12):e84272',
    link: 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0084272' },
  { n: 2, y: 2013, authors: 'Ko JS, Kim HJ, Han S, Do SH',
    title: 'Primary lymphoma of the uterine horn in a Lhasa Apso dog',
    journal: 'Irish Veterinary Journal', vol: '66(1):24',
    link: 'https://irishvetjournal.biomedcentral.com/articles/10.1186/2046-0481-66-24' },
  { n: 1, y: 2013, authors: 'Ko JS, Kim HJ, Choi YM, Kim JW, Park C, Do SH',
    title: 'Diagnostic approach to malignant fibrous histiocytomas of soft tissue in dogs: a case report',
    journal: 'Veterinarni Medicina', vol: '58(12):621-627',
    link: 'https://vetmed.agriculturejournals.cz/artkey/vet-201312-0007.php' },
];

Object.assign(window, { publications });
